--- 
- apk:
    name:  py-pip 
    state: present
    update_cache: yes
  when: ansible_distribution == 'Alpine'
- apt:
    name:  py-pip 
    state: present
    update_cache: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- pip:
    name:
      - azure-cli
    state: present 