--- 
 - name:    Install prerequisites Docker
   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
   apt:     name={{item}} update_cache=yes
   with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
 - name:    Add Docker GPG key
   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
   apt_key: url=https://download.docker.com/linux/ubuntu/gpg
 - name:    Add Docker APT repository
   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
   apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
 - name:    Install Docker
   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
   apt: name=docker-ce